### ISSUE TITLE
API_1_1 eGFX_PIXEL_RANDOM

### ISSUE THREAD

**Issue by alexanderhiam** [ehughes/eGFX#1]
On the API_1_1 branch, in `eGFX.c` you have:
```
if(PS == eGFX_PIXEL_RANDOM)
```
but `eGFX_PIXEL_RANDOM` is never actually defined: https://github.com/ehughes/eGFX/blob/API_1_1/SRC/eGFX.c#L97

Also, wouldn't special pixel states like that not actually work, as it's possible for a display to use the full 32 bits/pixel?

**Comment by ehughes** [comment]
That is an old definition from the 1st project that used an early form of the library.  At the time it was 3 color (red, green, yellow) so encoding a random pixel was easy.    

As for this line....  I and not sure what this was for.   THe 32-bit driver was for an APA102 panel project last fall (I used the lower 24 bits).   Maybe I defined it somewhere else.

You can blow it away.   It is possible it was test code that shouldn't have made it through.   I really need to refactor and clean things up!

**Comment by ehughes** [comment]
Issue fixed
